import type { Metadata } from "next";
import "./globals.css";
import { Rethink_Sans } from "next/font/google";

const RethinkSans = Rethink_Sans({
  subsets: ["latin"], // adjust subsets as needed
  // weight: ['400', '700'], // optionally specify weights if available
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={RethinkSans.className}>
        {children}
      </body>
    </html>
  );
}
